"""remove_default_model_id_from_templates

Revision ID: y1z2a3b4c5d6
Revises: x1y2z3a4b5c6
Create Date: 2026-05-14

Remove the default_model_id column from templates.
Model selection is now handled at the session, user, and skill
levels — templates focus purely on system prompt/personality.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "y1z2a3b4c5d6"
down_revision: Union[str, None] = "x1y2z3a4b5c6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Dynamically resolve the FK constraint name (auto-generated by MariaDB)
    connection = op.get_bind()
    inspector = sa.inspect(connection)
    columns = [c["name"] for c in inspector.get_columns("templates")]

    if "default_model_id" not in columns:
        # Column already removed — nothing to do
        return

    foreign_keys = inspector.get_foreign_keys("templates")
    fk_name = None
    for fk in foreign_keys:
        if fk.get("constrained_columns") == ["default_model_id"]:
            fk_name = fk["name"]
            break

    if fk_name:
        op.drop_constraint(fk_name, "templates", type_="foreignkey")
    op.drop_column("templates", "default_model_id")


def downgrade() -> None:
    op.add_column(
        "templates",
        sa.Column(
            "default_model_id",
            sa.CHAR(36),
            nullable=True,
        ),
    )
    op.create_foreign_key(
        None,
        "templates",
        "models",
        ["default_model_id"],
        ["id"],
    )
